version: '3'

services:
  my-mongodb:
   image: mongo:latest
   container_name: mongodb-local
   environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
   volumes:
    - ./data/db:/data/db
   ports:
    - 27017:27017
   command: mongod --smallfiles --logpath=/dev/null # --quiet
   networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge
