server:
  port: 17566

spring:
  cloud:
    gateway:
      default-filters:
        - name: SCGGlobalFilter
      routes:
        - id: sg-ms1
          uri: http://localhost:16876/
          predicates:
            - Path=/sg-ms1/**
          filters:
            - name: SCGPreFilter
            - name: SCGPostFilter
            - RewritePath=/sg-ms1/(?<segment>.*), /$\{segment}
        - id: sg-ms2
          uri: http://localhost:16877/
          predicates:
            - Path=/sg-ms2/**
          filters:
            - name: SCGPreFilter
            - RewritePath=/sg-ms2/(?<segment>.*), /$\{segment}